### ISSUE TITLE
eror padahal saya sudah masukkan link produk

### ISSUE THREAD

**Issue by ubed354311** [kevinopee/Autobuy-Shopee-ID#1]
Traceback (most recent call last):
  File "C:\Users\Asus\Downloads\Autobuy-Shopee-ID-main\Autobuy-Shopee-ID-main\Shopee Autobuy\save_cookies.py", line 109, in <module>
    main()
  File "C:\Users\Asus\Downloads\Autobuy-Shopee-ID-main\Autobuy-Shopee-ID-main\Shopee Autobuy\save_cookies.py", line 105, in main
    verif()
  File "C:\Users\Asus\Downloads\Autobuy-Shopee-ID-main\Autobuy-Shopee-ID-main\Shopee Autobuy\save_cookies.py", line 81, in verif
    click_login_button = WD(browser, 60).until(EC.element_to_be_clickable((
  File "C:\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by kevinopee** [comment]
Save cookies hanya untuk simpan akun situ biar nnti gaperlu login lagi. Readme dibaca dulu yaa, dibagian bawah yang step by step nya. Kasih star dong repo nya 😉🎉

**Comment by kevinopee** [comment]
Sudah saya update ya, untuk proses login pas di input kode verifikasi value nya read only, jadi gak ke send, jadi untuk kode verif input sendiri. Setelah itu baru cookies nya ke convert ke .pkl
